commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        timezone: 'America/New_York'
        currency: USD
        locale: en_US
        session_save: db
        admin_username: admin
        admin_firstname: Pat
        admin_lastname: Admin
        admin_password: password123
        admin_frontname: admin
        admin_email: pat.admin@example.org
        encryption_key:
        use_rewrites: no
        use_secure: no
    magento-packages:
      - name: magento-mirror-1.9.3.0
        version: 1.9.3.0
        source:
          url: https://github.com/OpenMage/magento-mirror/archive/1.9.3.0.zip
          type: zip
          shasum: a1f18d56c03f74207a712b12b2d93d7c524d1f1d
        extra:
          sample-data: sample-data-1.9.1.0
